In [95]:
import joblib
import math
import pandas as pd
import numpy as np

from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler

In [96]:
lrm_a = joblib.load('./models/lrm_a.pkl')

In [97]:
df = pd.read_csv('./data/test_data.txt', header=None, sep='\t')
df.rename(columns={0: 'MinTemp', 1: 'MaxTemp', 2: 'Precip'}, inplace=True)

In [98]:
df

MinTemp  MaxTemp  Precip
0     36.1111  21.1111   0.000
1     33.8889  26.6667   0.000
2     17.7778   7.2222   0.000
3     35.0000  24.4444   0.000
4     33.8889  19.4444   0.000
...       ...      ...     ...
4757  34.4444  20.0000   0.000
4758   1.1111  -2.2222   0.000
4759  30.5556  21.6667   0.000
4760  25.0000  19.4444   0.000
4761  20.0000  15.5556   0.254

[4762 rows x 3 columns]

In [99]:
X = df[['MinTemp', 'MaxTemp']]
Y = df['Precip']

In [100]:
test_scaler = StandardScaler()
test_scaler.fit(X)
X_tests_normed = test_scaler.transform(X)

In [114]:
test_scaler.mean_

array([27.16762236, 17.86142518])

In [113]:
test_scaler.scale_

array([8.43377541, 8.08615417])

In [101]:
Y_preds = lrm_a.predict(X_tests_normed)
print(f"mean squared error for test data: {mean_squared_error(Y, Y_preds)}")
print(f"root mean squared error for test data: {math.sqrt(mean_squared_error(Y, Y_preds))}")

mean squared error for test data: 104.36420540979294
root mean squared error for test data: 10.215880060464343


In [112]:
lrm_a.score(X_tests_normed, Y)

0.032429263804224395

In [103]:
Y

0       0.000
1       0.000
2       0.000
3       0.000
4       0.000
        ...  
4757    0.000
4758    0.000
4759    0.000
4760    0.000
4761    0.254
Name: Precip, Length: 4762, dtype: float64

In [104]:
Y.describe()

count    4762.000000
mean        3.099566
std        10.386758
min        -1.000000
25%         0.000000
50%         0.000000
75%         1.016000
max       157.480000
Name: Precip, dtype: float64

In [105]:
Y_preds

array([1.07056542, 4.67352742, 1.67936497, ..., 3.57773033, 4.73066599,
       4.84750671])

In [106]:
lrm_a.predict([X_tests_normed[4, :]])

array([1.15254373])

In [107]:
data = np.loadtxt('./data/test_data.txt', dtype=np.float32, delimiter='\t')
data = data[data[:, 2] <= 10, :]
data

array([[36.1111, 21.1111,  0.    ],
       [33.8889, 26.6667,  0.    ],
       [17.7778,  7.2222,  0.    ],
       ...,
       [30.5556, 21.6667,  0.    ],
       [25.    , 19.4444,  0.    ],
       [20.    , 15.5556,  0.254 ]], dtype=float32)

In [108]:
data[2, :2]

array([17.7778,  7.2222], dtype=float32)

In [109]:
data[2, 1]

7.2222

In [110]:
data[2, 0]

17.7778